### ISSUE TITLE
Readme shows wrong package name

### ISSUE THREAD

**Issue by chrismcband** [laginha/django-object-hooks#1]
Just a quick heads up, the readme mentions installing `django_object_hooks`, but it's actually `django-object-hooks` that's needed. Good job creating this, I found it following your issue on the django-rest-hooks, I have exactly the same use case, so hoping this does the job.

**Comment by laginha** [comment]
Feel free to contribute with improvements, bugfixes, documentation... unfortunately, I've not been able to dedicate any time to this.

**Comment by chrismcband** [comment]
Thanks, I'll get a pull-request sent your way when I get a chance. Working great by the way.

**Comment by chrismcband** [comment]
#2 should fix this.
